[tool.poetry]
name = "helpohelpo"
version = "0.5.0"
description = "A library of python helpers"
authors = ["Stablecaps <114529342+darkpandarts@users.noreply.github.com>"]
license = "LICENSE"
readme = "README.md"
keywords=[
    "python3",
    "helpers",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
packages = [{include = "helpo"}]


[tool.poetry.dependencies]
python = "^3.9"


# [tool.poetry.group.test.dependencies]
# pytest = "^7.2.2"
# requests-mock = "^1.10.0"
python-semantic-release = "^8.7.0"
dotmap = "^1.3.30"
ruamel-yaml = "^0.18.5"
pytest-cov = "^4.1.0"
arrow = "^1.3.0"
pydash = "^7.0.6"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.0"
black = "^23.12.1"
pytest = "^7.4.4"
python-semantic-release = "^8.7.0"
gpt4docstrings = "^0.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Homepage" = "https://github.com/stablecaps/helpohelpo"
"Bug Tracker" = "https://github.com/stablecaps/helpohelpo/issues"

#############################################
[tool.semantic_release]
version_variables = [
    "./__init__.py:__version__",
    "./pyproject.toml:version"
]
assets = []
version_source = "commit"
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "angular"
logging_use_named_masks = false
major_on_zero = false
tag_format = "{version}"
#
build_command = "poetry build"

[tool.semantic_release.branches.master]
match = "master"
prerelease_token = "rc"
prerelease = false

[tool.semantic_release.changelog]
template_dir = "templates"
changelog_file = "CHANGELOG.md"
exclude_commit_patterns = []

[tool.semantic_release.changelog.environment]
block_start_string = "{%"
block_end_string = "%}"
variable_start_string = "{{"
variable_end_string = "}}"
comment_start_string = "{#"
comment_end_string = "#}"
trim_blocks = false
lstrip_blocks = false
newline_sequence = "\n"
keep_trailing_newline = false
extensions = []
autoescape = true

[tool.semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "semantic-release <semantic-release>"

[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "style", "refactor", "test"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]

[tool.semantic_release.remote]
name = "origin"
type = "github"
ignore_token_for_push = true

[tool.semantic_release.remote.token]
env = "GH_TOKEN"

[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_vcs_release = true
#
#
#
#